# Docker-Composer para uso local
version: '3.7'

services:
  service_gateway:
    # Nombre del contenedor.
    container_name: container_gateway

    # Info de construcción del contenedor.
    build:
      # Directorio donde se encuentra el Dockerfile
      context: .
      # Nombre del Dockerfile
      dockerfile: Dockerfile

    entrypoint: ['./prod/entrypoint.sh']

    # TODO: Explicar esto
    volumes:
      - .:/usr/src/app/

    # Mapear puerto 5002 del contenedor al puerto 5002 de
    # sistema operativo.
    ports:
      - 5002:5002

    environment:
      - PORT=5002
      - PROJECTS_BACKEND_URL=https://seedy-fiuba-backend-projects.herokuapp.com
      - USERS_BACKEND_URL=https://seedy-fiuba-backend-users.herokuapp.com
      - PAYMENTS_BACKEND_URL=https://seedy-fiuba-backend-payments.herokuapp.com

    env_file:
      - .env

  test:
    # Nombre del contenedor.
    container_name: cont_test_gateway

    # Info de construcción del contenedor.
    build:
      # Directorio donde se encuentra el Dockerfile
      context: .
      # Nombre del Dockerfile
      dockerfile: Dockerfile.dev

    entrypoint: ['./prod/entrypoint.sh']

    # TODO: Explicar esto
    volumes:
      - .:/usr/src/app/

    # Mapear puerto 5002 del contenedor al puerto 5002 de
    # sistema operativo.
    ports:
      - 5010:5010

    environment:
      - PORT=5010
      - FLASK_ENV=development
      - FLASK_APP=./prod/manage
      - PROJECTS_BACKEND_URL=https://test-backend-projects.herokuapp.com
      - USERS_BACKEND_URL=https://test-backend-users.herokuapp.com
      - PAYMENTS_BACKEND_URL=https://test-backend-payments.herokuapp.com

    env_file:
      - .env

