# Docker-Composer para uso local
version: '3.7'

services:
  service_gateway:
    # Nombre del contenedor.
    container_name: container_gateway

    # Info de construcción del contenedor.
    build:
      # Directorio donde se encuentra el Dockerfile
      context: .
      # Nombre del Dockerfile
      dockerfile: Dockerfile

    entrypoint: ['./prod/entrypoint.sh']

    # TODO: Explicar esto
    volumes:
      - .:/usr/src/app/

    # Mapear puerto 5002 del contenedor al puerto 5002 de
    # sistema operativo.
    ports:
      - 5002:5002
